version: "2.27.0"
services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      rabbitmq:

  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./libs:/libs
    ports:
      - 3002:3000
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      rabbitmq:
      mongo-orders:
  mongo-orders:
    image: mongo
    volumes:
      - /data/orders
    ports:
      - 27019:27017
    networks:
      mongo-orders:



  customers:
    build:
      context: ./customers
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./libs:/libs
    ports:
      - 3001:3000
    depends_on:
      - rabbitmq
      - orders
    links:
      - rabbitmq
    networks:
      rabbitmq:
      mongo-customers:
  mongo-customers:
    image: mongo
    volumes:
      - /data/customers
    ports:
      - 27018:27017
    networks:
      mongo-customers:


  
  warehouse:
    build:
      context: ./warehouse
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./libs:/libs
    ports:
      - 3003:3000
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      rabbitmq:
      mongo-warehouse:
  mongo-warehouse:
    image: mongo
    volumes:
      - /data/warehouse
    ports:
      - 27020:27017
    networks:
      mongo-warehouse:

  supplier:
    build:
      context: ./third-party
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./libs:/libs
    ports:
      - 3004:3000
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      rabbitmq:
      mongo-supplier:
  mongo-supplier:
    image: mongo
    volumes:
      - /data/supplier
    ports:
      - 27021:27017
    networks:
      mongo-supplier:

  logistics:
    build:
      context: ./logistics
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./libs:/libs
    ports:
      - 3005:3000
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      rabbitmq:
      mongo-logistics:
  mongo-logistics:
    image: mongo
    volumes:
      - /data/logistics
    ports:
      - 27022:27017
    networks:
      mongo-logistics:

  finance:
    build:
      context: ./finance
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./libs:/libs
    ports:
      - 3006:3000
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      rabbitmq:
      mongo-finance:
  mongo-finance:
    image: mongo
    volumes:
      - /data/finance
    ports:
      - 27023:27017
    networks:
      mongo-finance:

networks:
  rabbitmq:
  mongo-customers:
  mongo-orders:
  mongo-warehouse:
  mongo-logistics:
  mongo-supplier:
  mongo-finance:
